language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

jdk:
  - oraclejdk8

script:
  - ./gradlew debugCoverageReport

notifications:
  email: false
